AWSTemplateFormatVersion: 2010-09-09
Description: |
  Author: eversojoe@github
  Deploys tool to save cost on ebs volumes for a specific instance that is not run 24/7
Parameters:
  InstanceId:
    Type: String
    Description: Instance ID of the instance that should be controlled 
  MountPoint:
    Type: String
    Description: Mount point (Device) to which the restored volume should be mounted to
  LambdaCodeBucket:
    Type: String
    Description: Name of the Bucket the Lambda code resides in
  LambdaStartCodeKey:
    Type: String
    Description: Name of the Bucket key the Start Lambda code resides on
  LambdaStopCodeKey:
    Type: String
    Description: Name of the Bucket key the Stop Lambda code resides on

Resources:
  SSMPARAMETER:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: NaN
  ROLE:
    Type: AWS::IAM::Role
    Properties:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:DescribeInstances'
                  - 'ec2:StopInstances'
                  - 'ec2:DescribeVolumes'
                  - 'ec2:CreateSnapshot'
                  - 'ec2:PutSnapshotBlock'
                  - 'ec2:CreateTags'
                  - 'ec2:DetachVolume'
                  - 'ec2:DeleteVolume'
                  - 'ssm:GetParameter'
                  - 'ssm:PutParameter'
                Resource:
                  - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/${InstanceID}"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${SSMPARAMETER}"
  LAMBDASTART:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaStartCodeKey
      Environment:
        Variables:
          MOUNT_POINT: !Ref MountPoint
          SSM_PARAMETER: !Ref SSMPARAMETER
          INSTANCE_ID: !Ref InstanceId
      Handler: function.handler
      Role: !Ref ROLE 
      Runtime: python3.11
      Timeout: 360

  LAMBDASTOP:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaStopCodeKey
      Environment:
        Variables:
          SSM_PARAMETER: !Ref SSMPARAMETER
          INSTANCE_ID: !Ref InstanceId
      Handler: function.handler
      Role: !Ref ROLE 
      Runtime: python3.11
      Timeout: 360