AWSTemplateFormatVersion: 2010-09-09
Description: |
  Author: eversojoe@github
  Deploys tool to save cost on ebs volumes for a specific instance that is not run 24/7
Parameters:
  InstanceId:
    Type: String
    Description: Instance ID of the instance that should be controlled 
  MountPoint:
    Type: String
    Description: Mount point (Device) to which the restored volume should be mounted to
  LambdaCodeBucket:
    Type: String
    Description: Name of the Bucket the Lambda code resides in
  LambdaStartCodeKey:
    Type: String
    Description: Name of the Bucket key the Start Lambda code resides on
  LambdaStopCodeKey:
    Type: String
    Description: Name of the Bucket key the Stop Lambda code resides on

Resources:
  SSMPARAMETER:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: NaN
  ROLE:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: JSON # Required
      ManagedPolicyArns: 
        ManagedPolicyArns
      Policies: 
        Policies
  LAMBDASTART:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaStartCodeKey
      Environment:
        Variables:
          MOUNT_POINT: !Ref MountPoint
          SSM_PARAMETER: !Ref SSMPARAMETER
          INSTANCE_ID: !Ref InstanceId
      Handler: function.handler
      Role: !Ref ROLE 
      Runtime: python3.11
      Timeout: 360

  LAMBDASTOP:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaStopCodeKey
      Environment:
        Variables:
          SSM_PARAMETER: !Ref SSMPARAMETER
          INSTANCE_ID: !Ref InstanceId
      Handler: function.handler
      Role: !Ref ROLE 
      Runtime: python3.11
      Timeout: 360